# Generated by Django 5.2.13 on 2026-04-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('logo_colour', models.CharField(default='#3B82F6', max_length=7)),
                ('mode', models.CharField(choices=[('batch', 'Batch'), ('person', 'Person')], default='person', max_length=10)),
                ('batch_size', models.PositiveIntegerField(default=5)),
                ('twilio_from_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='StaffPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_phones', to='businesses.business')),
            ],
            options={
                'unique_together': {('phone', 'business')},
            },
        ),
    ]
