# Generated by Django 5.2.13 on 2026-04-24 05:13

import businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='sms_template',
            field=models.CharField(default="You're being called! Please proceed to {business_name}.", help_text='Placeholders: {business_name}, {customer_name}.', max_length=320),
        ),
        migrations.AlterField(
            model_name='business',
            name='twilio_from_number',
            field=models.CharField(blank=True, max_length=20, validators=[businesses.models._validate_e164]),
        ),
    ]
