# Generated by Django 5.2.13 on 2026-04-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_sms_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(default='CA', help_text='ISO 3166-1 alpha-2 country code. Used to validate customer phone numbers on join.', max_length=2),
        ),
    ]
