# Generated by Django 5.2.13 on 2026-04-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='avg_service_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
