# Generated by Django 5.2.13 on 2026-04-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_avg_service_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_closing',
            field=models.BooleanField(default=False),
        ),
    ]
