# Generated by Django 5.2.13 on 2026-04-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_add_is_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='menu_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
