# Generated by Django 5.2.13 on 2026-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_pickup_feature_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pickup_intake_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
