# Generated by Django 5.2.13 on 2026-05-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_logo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pos_api_token',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='business',
            name='pos_merchant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='pos_type',
            field=models.CharField(choices=[('none', 'None'), ('clover', 'Clover'), ('square', 'Square')], default='none', max_length=10),
        ),
    ]
