# Generated by Django 5.2.13 on 2026-05-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_pos_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_identifier',
            field=models.CharField(choices=[('name', 'Name'), ('order_number', 'Order number'), ('phone', 'Phone number')], default='name', help_text='Primary field shown to customers when registering a pickup order.', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='toast_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='toast_client_secret',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='business',
            name='pos_type',
            field=models.CharField(choices=[('none', 'None'), ('clover', 'Clover'), ('square', 'Square'), ('toast', 'Toast'), ('lightspeed', 'Lightspeed')], default='none', max_length=20),
        ),
    ]
