# Generated by Django 5.2.13 on 2026-05-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_toast_lightspeed_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='field_name_enabled',
            field=models.BooleanField(default=True, help_text='Show the customer name field on the pickup join form.'),
        ),
        migrations.AddField(
            model_name='business',
            name='field_name_required',
            field=models.BooleanField(default=True, help_text='Require a name before the form can be submitted.'),
        ),
        migrations.AddField(
            model_name='business',
            name='field_order_number_enabled',
            field=models.BooleanField(default=False, help_text='Show an order number field on the pickup join form.'),
        ),
        migrations.AddField(
            model_name='business',
            name='field_order_number_required',
            field=models.BooleanField(default=False, help_text='Require an order number before the form can be submitted.'),
        ),
        migrations.AddField(
            model_name='business',
            name='field_phone_enabled',
            field=models.BooleanField(default=True, help_text='Phone number is always shown (needed for SMS notifications).'),
        ),
        migrations.AddField(
            model_name='business',
            name='field_phone_required',
            field=models.BooleanField(default=False, help_text='Require a phone number before the form can be submitted.'),
        ),
    ]
