# Generated by Django 5.2.13 on 2026-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_join_field_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pickup_show_wait_estimate',
            field=models.BooleanField(default=False),
        ),
    ]
