# Generated by Django 5.2.13 on 2026-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_add_pickup_show_wait_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pickup_tag_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
