# Generated by Django 5.2.13 on 2026-04-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('skipped', 'Skipped')], default='waiting', max_length=10)),
                ('position', models.PositiveIntegerField()),
                ('batch_number', models.PositiveIntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='businesses.business')),
            ],
            options={
                'verbose_name_plural': 'queue entries',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='QueueEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('joined', 'Joined'), ('called', 'Called'), ('skipped', 'Skipped'), ('abandoned', 'Abandoned'), ('sms_sent', 'SMS Sent'), ('sms_failed', 'SMS Failed')], max_length=20)),
                ('before_values', models.JSONField(default=dict)),
                ('after_values', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='businesses.business')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='queues.queueentry')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
