# Generated by Django 5.2.13 on 2026-04-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_pickupentry_pickupeventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='pickupeventlog',
            name='event_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('ready', 'Ready'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled'), ('sms_sent', 'SMS Sent'), ('sms_failed', 'SMS Failed'), ('closing_soon_sms', 'Closing Soon SMS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='queueeventlog',
            name='event_type',
            field=models.CharField(choices=[('joined', 'Joined'), ('called', 'Called'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('abandoned', 'Abandoned'), ('sms_sent', 'SMS Sent'), ('sms_failed', 'SMS Failed'), ('late_arrival', 'Late Arrival'), ('left', 'Left'), ('queue_cleared', 'Queue Cleared'), ('closing_soon_sms', 'Closing Soon SMS')], max_length=20),
        ),
    ]
