# Generated by Django 5.2.13 on 2026-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_pickup_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupentry',
            name='intake_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
