# Generated by Django 5.2.13 on 2026-05-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_pickup_intake_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupentry',
            name='pos_match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickupentry',
            name='pos_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pickupentry',
            name='pos_order_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
