# Generated by Django 5.2.13 on 2026-05-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_pos_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupentry',
            name='pos_order_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickupentry',
            name='pos_order_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pickupentry',
            name='pos_order_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
