# Generated by Django 5.2.13 on 2026-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_pickup_pos_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupeventlog',
            name='event_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('ready', 'Ready'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled'), ('sms_sent', 'SMS Sent'), ('sms_failed', 'SMS Failed'), ('closing_soon_sms', 'Closing Soon SMS'), ('tags_reset', 'Tags Reset')], max_length=20),
        ),
    ]
